class_name TransferType

const TYPE_LOGIN = "LOGIN"
const TYPE_ROOM_CREATE = "CREATE_ROOM"
const TYPE_ROOM_INVITE_PERSON = "INVITE_PERSON"
const TYPE_ROOM_INVITE_CONFIRM = "INVITE_CONFIRM"
const TYPE_ROOM_INVITE_ME = "INVITE_ME"
const TYPE_ROOM_REFRESH = "PERSON_REFRESH"
