class_name TransferType

const TYPE_LOGIN = "LOGIN"
const TYPE_ROOM_CREATE = "CREATE_ROOM"
const TYPE_ROOM_INVITE_PERSON = "INVITE_PERSON"
const TYPE_ROOM_INVITE_CONFIRM = "INVITE_CONFIRM"
const TYPE_ROOM_INVITE_ME = "INVITE_ME"
const TYPE_ROOM_REFRESH = "PERSON_REFRESH"
const TYPE_ROOM_START = "PLAY_START"
const TYPE_ROOM_START_RES = "ROOM_PLAY"

const TYPE_PLAY_INIT_LINES = "INIT_LINES"
const TYPE_PLAY_GOT_LINE = "GOT_LINE"
const TYPE_PLAY_NEXT_LINE = "NEXT_LINE"
const TYPE_PLAY_GOT_EVENT = "GOT_EVENT"
const TYPE_PLAY_EVENT = "EVENT"
const TYPE_PLAY_UPDATE_SCORE = "SCORE_UPDATE"
const TYPE_PLAY_ROOM_SCORE_UPDATE = "ROOM_SCORE_UPDATE"
